#!/usr/bin/env python
import os,sys
sys.path.append('.build_utils')
from build_utils import *

erlc('server')
erlc('zhandler')
erlc('character')
erlc('scenario')
erlc('zombie')
erlc('tile')
erlc('nav')
erlc('los')
erlc('tick')
